# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gin-demo
  name: gin-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gin-demo
  template:
    metadata:
      labels:
        app: gin-demo
    spec:
      containers:
      - name: gin-demo
        image: registry.cn-hangzhou.aliyuncs.com/zzrr_images/gin-demo:v1
        ports:
        - containerPort: 8080
